### ISSUE TITLE
grammer fixes, redrive policy

### ISSUE THREAD

**Issue by kevinrs5855** [awsdocs/amazon-sqs-developer-guide#1]
The documentation on SQS dead letter queues is mentioning a redrive policy.  I think it should be mentioning a retry policy.

https://docs.aws.amazon.com/AWSSimpleQueueService/latest/SQSDeveloperGuide/sqs-dead-letter-queues.html

**Comment by mig281** [comment]
@kevinrs5855 Thank you for your feedback! "Redrive policy" is actually correct. For more information,
 see [Configuring an Amazon SQS Dead-Letter Queue](https://docs.aws.amazon.com/AWSSimpleQueueService/latest/SQSDeveloperGuide/sqs-configure-dead-letter-queue.html) and the [RedrivePolicy attribute of the SetQueueAttributes API action](https://docs.aws.amazon.com/AWSSimpleQueueService/latest/APIReference/API_SetQueueAttributes.html).
