### ISSUE TITLE
SQS Pricing page place holder

### ISSUE THREAD

**Issue by davidkhala** [awsdocs/amazon-sqs-developer-guide#17]
Sorry first for that this problem might not under the scope of developer guide, but I could not find anywhere or suitable support category to report it. 

In the site https://aws.amazon.com/sqs/pricing/

I find a meaningless place holder content under section 
**Learn how to get started**
Quisque laoreet rhoncus rutrum. Sed nec lectus orci. Duis et nulla sit amet nisi finibus sagittis vitae vel arcu.

Hope any maintainer from AWS team could notify related teammates to fix it. 

All the best.

**Comment by mig281** [comment]
@davidkhala Thank you very much for bringing this to my attention. I don't have the required permissions to edit the page in question directly. Having said this, I've notified the PM for Amazon SQS and the issue should be corrected soon.

**Comment by davidkhala** [comment]
You are helpful. Thanks
