### ISSUE TITLE
Docs can be interpreted to imply that the SQS visibility timeout maximum is relative to SendMesssage requests rather than ReceiveMessage requests

### ISSUE THREAD

**Issue by bascarsija** [awsdocs/amazon-sqs-developer-guide#25]
From PR #24:

The current language reads:

> The maximum visibility timeout is 12 hours from the time that Amazon SQS receives the message. Extending the visibility timeout does not reset the 12-hour maximum.

This is problematic, as "message" is used pervasively in the SQS documentation to refer specifically to the data plane entries stored in SQS queues, as differentiated from "request," which refers to a request intended to interact with the SQS control plane.

As written currently, it is easily misinterpreted to imply that there is a 12-hour maximum on visibility timeouts that begins when messages are enqueued (i.e. "from the time that Amazon SQS receives the message"), which would mean that the message retention periods for SQS FIFOs must correspondingly be set to less than 12 hours to ensure that messages are not received and processed out of order by concurrent consumers in a race.

**Comment by carlasp** [comment]
Thank you for reaching out! I've fixed this.
