### ISSUE TITLE
What does this mean?  IAM policy of the producer

### ISSUE THREAD

**Issue by dexterlakin** [awsdocs/amazon-sqs-developer-guide#37]
@devlinbd2
RE: https://github.com/awsdocs/amazon-sqs-developer-guide/blame/main/doc_source/sqs-key-management.md#L58

What is meant by the IAM policy of the producer?

An SNS Topic is our producer but the only IAM policies attached to it are for delivery status logging and the access policy (This policy defines who can access your topic).

**Comment by SUJAYJHORA** [comment]
@ #
[Uploading u.pdf…]()

**Comment by SUJAYJHORA** [comment]
Yex time

**Comment by amboller** [comment]
Thank you for your feedback. I'll add it to the team's list of items for future consideration and then close this issue.

**Comment by joshbean** [comment]
Closing this issue or pull request in advance of archiving this repo. For more information about the decision to archive this repo (and others in the 'awsdocs' org), see [the announcement on the AWS News Blog](https://aws.amazon.com/blogs/aws/retiring-the-aws-documentation-on-github/).
