### ISSUE TITLE
Message visibility timeout 

### ISSUE THREAD

**Issue by martysweet** [awsdocs/amazon-sqs-developer-guide#4]
Throughout the SQS Developer Guide the following sentence is repeated:

> The default (minimum) visibility timeout for a message is 30 seconds. The maximum is 12 hours.

This makes it seem like the minimum visibility timeout is 30 seconds and the maximum value is 12 hours, however, the API (and console) state the minimum value is 0 seconds.

> VisibilityTimeout - The visibility timeout for the queue, in seconds. Valid values: An integer from 0 to 43,200 (12 hours).

https://docs.aws.amazon.com/AWSSimpleQueueService/latest/APIReference/API_CreateQueue.html

Have I missed a certain detail which makes it 30 seconds? Or do the docs need further clarification, for example:

> The default visibility timeout for a message is 30 seconds. The minimum is 0 seconds. The maximum is 12 hours.

Happy to submit a PR either way to help others!

Marty

**Comment by mig281** [comment]
P.S. The update will be reflected in the GitHub version shortly.
