### ISSUE TITLE
SQS FIFO Queue Order Information

### ISSUE THREAD

**Issue by gozeloglu** [awsdocs/amazon-sqs-developer-guide#44]
In [here](https://github.com/awsdocs/amazon-sqs-developer-guide/blob/main/doc_source/sqs-dead-letter-queues.md#:~:text=Don%27t%20use%20a%20dead%2Dletter%20queue%20with%20a%20FIFO%20queue%20if%20you%20don%27t%20want%20to%20break%20the%20exact%20order%20of%20messages%20or%20operations.), it says that **Don't use a dead-letter queue with a FIFO queue if you don't want to break the exact order of messages or operations.**. As I understood that we use FIFO for preserving orders, but the documentation says the opposite. Am I missing something or the documentation is wrong?

**Comment by amboller** [comment]
Thank you for your request. I'll add it to the team's list of items for future consideration and then close this issue.

**Comment by gozeloglu** [comment]
Thank you. I can fix it if you want. Don't hesitate to assign me.

**Comment by amboller** [comment]
Feel free to to perform a pull request with your update!
