### ISSUE TITLE
AWS SQS dead-letter queue redrive policy

### ISSUE THREAD

**Issue by sskanishk** [awsdocs/amazon-sqs-developer-guide#46]
In my system there is a main-queue and dead-letter-queue.

When any message failed in main-queue it goes to dead-letter-queue.

Reason of failing message in main-queue sometime random not critical i.e. message can be processed if reattempt from the main-queue.

There are 3 attempt to any failed message, meaning will send message to main-queue from dead-letter-queue only 3 times.

How can i track the message whether its 3rd attempt is exhausted and there is no need to send it back to main-queue for processing (will keep in dlq till it expire)?

**Comment by joshbean** [comment]
Closing this issue or pull request in advance of archiving this repo. For more information about the decision to archive this repo (and others in the 'awsdocs' org), see [the announcement on the AWS News Blog](https://aws.amazon.com/blogs/aws/retiring-the-aws-documentation-on-github/).
