### ISSUE TITLE
graphic explanation is not clear

### ISSUE THREAD

**Issue by vodelerk** [awsdocs/amazon-sqs-developer-guide#49]
I don't understand this graphic for this explanation, it should be reviewed

**Comment by joshbean** [comment]
Closing this issue or pull request in advance of archiving this repo. For more information about the decision to archive this repo (and others in the 'awsdocs' org), see [the announcement on the AWS News Blog](https://aws.amazon.com/blogs/aws/retiring-the-aws-documentation-on-github/).
