### ISSUE TITLE
Add deduplication scope to doc

### ISSUE THREAD

**Issue by lpiedade** [awsdocs/amazon-sqs-developer-guide#55]
This note "Message deduplication applies to an entire queue, not to individual message groups." it's not always true considering the deduplication scope option: "Message Group" level. 

Doc Link: 
https://docs.aws.amazon.com/AWSSimpleQueueService/latest/SQSDeveloperGuide/using-messagededuplicationid-property.html

**Comment by joshbean** [comment]
Closing this issue or pull request in advance of archiving this repo. For more information about the decision to archive this repo (and others in the 'awsdocs' org), see [the announcement on the AWS News Blog](https://aws.amazon.com/blogs/aws/retiring-the-aws-documentation-on-github/).
